/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/logo/m3-logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/m3-logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.path250.geometry} material={materials['SVGMat.001']} scale={0.001} />
      <mesh geometry={nodes.path248.geometry} material={materials['SVGMat.002']} scale={0.001} />
      <mesh geometry={nodes.path246.geometry} material={materials['SVGMat.003']} scale={0.001} />
      <mesh geometry={nodes.path244.geometry} material={materials['SVGMat.004']} scale={0.001} />
      <mesh geometry={nodes.path242.geometry} material={materials['SVGMat.005']} scale={0.001} />
      <mesh geometry={nodes.path240.geometry} material={materials['SVGMat.006']} scale={0.001} />
      <mesh geometry={nodes.path238.geometry} material={materials['SVGMat.007']} scale={0.001} />
      <mesh geometry={nodes.path236.geometry} material={materials['SVGMat.008']} scale={0.001} />
      <mesh geometry={nodes.path234.geometry} material={materials['SVGMat.009']} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/m3-logo.glb')
